#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_DUSTY_1                      42
#define TRAINER_CHIP                         43
#define TRAINER_FOSTER                       44
#define TRAINER_DUSTY_2                      45
#define TRAINER_DUSTY_3                      46
#define TRAINER_GABBY_AND_TY_1               47
#define TRAINER_GABBY_AND_TY_2               48
#define TRAINER_GABBY_AND_TY_3               49
#define TRAINER_GABBY_AND_TY_4               50
#define TRAINER_GABBY_AND_TY_5               51
#define TRAINER_GABBY_AND_TY_6               52
#define TRAINER_LOLA_1                       53
#define TRAINER_AUSTINA                      54
#define TRAINER_GWEN                         55
#define TRAINER_LOLA_2                       56
#define TRAINER_LOLA_3                       57
#define TRAINER_RICKY_1                      58
#define TRAINER_SIMON                        59
#define TRAINER_CHARLIE                      60
#define TRAINER_RICKY_2                      61
#define TRAINER_RICKY_3                      62
#define TRAINER_RANDALL                      63
#define TRAINER_PARKER                       64
#define TRAINER_GEORGE                       65
#define TRAINER_BERKE                        66
#define TRAINER_BRAXTON                      67
#define TRAINER_VINCENT                      68
#define TRAINER_LEROY                        69
#define TRAINER_WILTON_1                     70
#define TRAINER_EDGAR                        71
#define TRAINER_ALBERT                       72
#define TRAINER_SAMUEL                       73
#define TRAINER_VITO                         74
#define TRAINER_OWEN                         75
#define TRAINER_WILTON_2                     76
#define TRAINER_WILTON_3                     77
#define TRAINER_WARREN                       78
#define TRAINER_MARY                         79
#define TRAINER_ALEXIA                       80
#define TRAINER_JODY                         81
#define TRAINER_WENDY                        82
#define TRAINER_KEIRA                        83
#define TRAINER_BROOKE_1                     84
#define TRAINER_JENNIFER                     85
#define TRAINER_HOPE                         86
#define TRAINER_SHANNON                      87
#define TRAINER_MICHELLE                     88
#define TRAINER_CAROLINE                     89
#define TRAINER_JULIE                        90
#define TRAINER_BROOKE_2                     91
#define TRAINER_BROOKE_3                     92
#define TRAINER_PATRICIA                     93
#define TRAINER_KINDRA                       94
#define TRAINER_TAMMY                        95
#define TRAINER_VALERIE_1                    96
#define TRAINER_TASHA                        97
#define TRAINER_VALERIE_2                    98
#define TRAINER_VALERIE_3                    99
#define TRAINER_CINDY_1                     100
#define TRAINER_DAPHNE                      101
#define TRAINER_GRUNT_SPACE_CENTER_2        102
#define TRAINER_BRIANNA                     103
#define TRAINER_NAOMI                       104
#define TRAINER_CINDY_2                     105
#define TRAINER_CINDY_3                     106
#define TRAINER_MELISSA                     107
#define TRAINER_SHEILA                      108
#define TRAINER_SHIRLEY                     109
#define TRAINER_JESSICA_1                   110
#define TRAINER_CONNIE                      111
#define TRAINER_BRIDGET                     112
#define TRAINER_OLIVIA                      113
#define TRAINER_TIFFANY                     114
#define TRAINER_JESSICA_2                   115
#define TRAINER_JESSICA_3                   116
#define TRAINER_WINSTON_1                   117
#define TRAINER_MOLLIE                      118
#define TRAINER_GARRET                      119
#define TRAINER_WINSTON_2                   120
#define TRAINER_WINSTON_3                   121
#define TRAINER_STEVE_1                     122
#define TRAINER_THALIA_1                    123
#define TRAINER_MARK                        124
#define TRAINER_GRUNT_MT_CHIMNEY_1          125
#define TRAINER_STEVE_2                     126
#define TRAINER_STEVE_3                     127
#define TRAINER_LUIS                        128
#define TRAINER_DOMINIK                     129
#define TRAINER_DOUGLAS                     130
#define TRAINER_DARRIN                      131
#define TRAINER_TONY_1                      132
#define TRAINER_JEROME                      133
#define TRAINER_MATTHEW                     134
#define TRAINER_DAVID                       135
#define TRAINER_SPENCER                     136
#define TRAINER_ROLAND                      137
#define TRAINER_NOLEN                       138
#define TRAINER_STAN                        139
#define TRAINER_BARRY                       140
#define TRAINER_DEAN                        141
#define TRAINER_RODNEY                      142
#define TRAINER_RICHARD                     143
#define TRAINER_HERMAN                      144
#define TRAINER_SANTIAGO                    145
#define TRAINER_GILBERT                     146
#define TRAINER_FRANKLIN                    147
#define TRAINER_KEVIN                       148
#define TRAINER_JACK                        149
#define TRAINER_DUDLEY                      150
#define TRAINER_CHAD                        151
#define TRAINER_TONY_2                      152
#define TRAINER_TONY_3                      153
#define TRAINER_TAKAO                       154
#define TRAINER_HITOSHI                     155
#define TRAINER_KIYO                        156
#define TRAINER_KOICHI                      157
#define TRAINER_NOB_1                       158
#define TRAINER_NOB_2                       159
#define TRAINER_NOB_3                       160
#define TRAINER_YUJI                        161
#define TRAINER_DAISUKE                     162
#define TRAINER_ATSUSHI                     163
#define TRAINER_KIRK                        164
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        165
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        166
#define TRAINER_SHAWN                       167
#define TRAINER_FERNANDO_1                  168
#define TRAINER_DALTON_1                    169
#define TRAINER_DALTON_2                    170
#define TRAINER_DALTON_3                    171
#define TRAINER_COLE                        172
#define TRAINER_JEFF                        173
#define TRAINER_AXLE                        174
#define TRAINER_JACE                        175
#define TRAINER_KEEGAN                      176
#define TRAINER_BERNIE_1                    177
#define TRAINER_BERNIE_2                    178
#define TRAINER_BERNIE_3                    179
#define TRAINER_DREW                        180
#define TRAINER_BEAU                        181
#define TRAINER_LARRY                       182
#define TRAINER_SHANE                       183
#define TRAINER_JUSTIN                      184
#define TRAINER_ETHAN_1                     185
#define TRAINER_AUTUMN                      186
#define TRAINER_TRAVIS                      187
#define TRAINER_ETHAN_2                     188
#define TRAINER_ETHAN_3                     189
#define TRAINER_BRENT                       190
#define TRAINER_DONALD                      191
#define TRAINER_TAYLOR                      192
#define TRAINER_JEFFREY_1                   193
#define TRAINER_DEREK                       194
#define TRAINER_JEFFREY_2                   195
#define TRAINER_JEFFREY_3                   196
#define TRAINER_EDWARD                      197
#define TRAINER_PRESTON                     198
#define TRAINER_VIRGIL                      199
#define TRAINER_BLAKE                       200
#define TRAINER_WILLIAM                     201
#define TRAINER_JOSHUA                      202
#define TRAINER_CAMERON_1                   203
#define TRAINER_CAMERON_2                   204
#define TRAINER_CAMERON_3                   205
#define TRAINER_JACLYN                      206
#define TRAINER_HANNAH                      207
#define TRAINER_SAMANTHA                    208
#define TRAINER_MAURA                       209
#define TRAINER_KAYLA                       210
#define TRAINER_ALEXIS                      211
#define TRAINER_JACKI_1                     212
#define TRAINER_JACKI_2                     213
#define TRAINER_JACKI_3                     214
#define TRAINER_WALTER_1                    215
#define TRAINER_MICAH                       216
#define TRAINER_THOMAS                      217
#define TRAINER_WALTER_2                    218
#define TRAINER_WALTER_3                    219
#define TRAINER_SIDNEY                      220
#define TRAINER_PHOEBE                      221
#define TRAINER_GLACIA                      222
#define TRAINER_DRAKE                       223
#define TRAINER_ROXANNE_1                   224
#define TRAINER_BRAWLY_1                    225
#define TRAINER_WATTSON_1                   226
#define TRAINER_FLANNERY_1                  227
#define TRAINER_NORMAN_1                    228
#define TRAINER_WINONA_1                    229
#define TRAINER_TATE_AND_LIZA_1             230
#define TRAINER_JUAN_1                      231
#define TRAINER_JERRY_1                     232
#define TRAINER_TED                         233
#define TRAINER_PAUL                        234
#define TRAINER_JERRY_2                     235
#define TRAINER_JERRY_3                     236
#define TRAINER_KAREN_1                     237
#define TRAINER_GEORGIA                     238
#define TRAINER_KAREN_2                     239
#define TRAINER_KAREN_3                     240
#define TRAINER_KATE_AND_JOY                241
#define TRAINER_ANNA_AND_MEG_1              242
#define TRAINER_ANNA_AND_MEG_2              243
#define TRAINER_ANNA_AND_MEG_3              244
#define TRAINER_VICTOR                      245
#define TRAINER_MIGUEL_1                    246
#define TRAINER_COLTON                      247
#define TRAINER_MIGUEL_2                    248
#define TRAINER_MIGUEL_3                    249
#define TRAINER_VICTORIA                    250
#define TRAINER_VANESSA                     251
#define TRAINER_BETHANY                     252
#define TRAINER_ISABEL_1                    253
#define TRAINER_ISABEL_2                    254
#define TRAINER_ISABEL_3                    255
#define TRAINER_TIMOTHY_1                   256
#define TRAINER_TIMOTHY_2                   257
#define TRAINER_TIMOTHY_3                   258
#define TRAINER_VICKY                       259
#define TRAINER_SHELBY_1                    260
#define TRAINER_SHELBY_2                    261
#define TRAINER_SHELBY_3                    262
#define TRAINER_CALVIN_1                    263
#define TRAINER_BILLY                       264
#define TRAINER_JOSH                        265
#define TRAINER_TOMMY                       266
#define TRAINER_JOEY                        267
#define TRAINER_BEN                         268
#define TRAINER_QUINCY                      269
#define TRAINER_KATELYNN                    270
#define TRAINER_JAYLEN                      271
#define TRAINER_DILLON                      272
#define TRAINER_CALVIN_2                    273
#define TRAINER_CALVIN_3                    274
#define TRAINER_EDDIE                       275
#define TRAINER_ALLEN                       276
#define TRAINER_TIMMY                       277
#define TRAINER_WALLACE                     278
#define TRAINER_ANDREW                      279
#define TRAINER_IVAN                        280
#define TRAINER_CLAUDE                      281
#define TRAINER_ELLIOT_1                    282
#define TRAINER_NED                         283
#define TRAINER_DALE                        284
#define TRAINER_NOLAN                       285
#define TRAINER_BARNY                       286
#define TRAINER_WADE                        287
#define TRAINER_CARTER                      288
#define TRAINER_ELLIOT_2                    289
#define TRAINER_ELLIOT_3                    290
#define TRAINER_RONALD                      291
#define TRAINER_JACOB                       292
#define TRAINER_ANTHONY                     293
#define TRAINER_BENJAMIN_1                  294
#define TRAINER_BENJAMIN_2                  295
#define TRAINER_BENJAMIN_3                  296
#define TRAINER_ABIGAIL_1                   297
#define TRAINER_JASMINE                     298
#define TRAINER_ABIGAIL_2                   299
#define TRAINER_ABIGAIL_3                   300
#define TRAINER_DYLAN_1                     301
#define TRAINER_DYLAN_2                     302
#define TRAINER_DYLAN_3                     303
#define TRAINER_MARIA_1                     304
#define TRAINER_MARIA_2                     305
#define TRAINER_MARIA_3                     306
#define TRAINER_CAMDEN                      307
#define TRAINER_DEMETRIUS                   308
#define TRAINER_ISAIAH_1                    309
#define TRAINER_PABLO_1                     310
#define TRAINER_CHASE                       311
#define TRAINER_ISAIAH_2                    312
#define TRAINER_ISAIAH_3                    313
#define TRAINER_ISOBEL                      314
#define TRAINER_DONNY                       315
#define TRAINER_TALIA                       316
#define TRAINER_KATELYN_1                   317
#define TRAINER_ALLISON                     318
#define TRAINER_KATELYN_2                   319
#define TRAINER_KATELYN_3                   320
#define TRAINER_NICOLAS_1                   321
#define TRAINER_NICOLAS_2                   322
#define TRAINER_NICOLAS_3                   323
#define TRAINER_AARON                       324
#define TRAINER_PERRY                       325
#define TRAINER_HUGH                        326
#define TRAINER_PHIL                        327
#define TRAINER_JARED                       328
#define TRAINER_HUMBERTO                    329
#define TRAINER_PRESLEY                     330
#define TRAINER_EDWARDO                     331
#define TRAINER_COLIN                       332
#define TRAINER_ROBERT_1                    333
#define TRAINER_BENNY                       334
#define TRAINER_CHESTER                     335
#define TRAINER_ROBERT_2                    336
#define TRAINER_ROBERT_3                    337
#define TRAINER_ALEX                        338
#define TRAINER_BECK                        339
#define TRAINER_YASU                        340
#define TRAINER_TAKASHI                     341
#define TRAINER_DIANNE                      342
#define TRAINER_JANI                        343
#define TRAINER_LAO_1                       344
#define TRAINER_LUNG                        345
#define TRAINER_LAO_2                       346
#define TRAINER_LAO_3                       347
#define TRAINER_JOCELYN                     348
#define TRAINER_LAURA                       349
#define TRAINER_CYNDY_1                     350
#define TRAINER_CORA                        351
#define TRAINER_PAULA                       352
#define TRAINER_CYNDY_2                     353
#define TRAINER_CYNDY_3                     354
#define TRAINER_MADELINE_1                  355
#define TRAINER_CLARISSA                    356
#define TRAINER_ANGELICA                    357
#define TRAINER_MADELINE_2                  358
#define TRAINER_MADELINE_3                  359
#define TRAINER_BEVERLY                     360
#define TRAINER_IMANI                       361
#define TRAINER_KYLA                        362
#define TRAINER_DENISE                      363
#define TRAINER_BETH                        364
#define TRAINER_TARA                        365
#define TRAINER_MISSY                       366
#define TRAINER_ALICE                       367
#define TRAINER_JENNY_1                     368
#define TRAINER_GRACE                       369
#define TRAINER_TANYA                       370
#define TRAINER_SHARON                      371
#define TRAINER_NIKKI                       372
#define TRAINER_BRENDA                      373
#define TRAINER_KATIE                       374
#define TRAINER_SUSIE                       375
#define TRAINER_KARA                        376
#define TRAINER_DANA                        377
#define TRAINER_SIENNA                      378
#define TRAINER_DEBRA                       379
#define TRAINER_LINDA                       380
#define TRAINER_KAYLEE                      381
#define TRAINER_LAUREL                      382
#define TRAINER_CARLEE                      383
#define TRAINER_JENNY_2                     384
#define TRAINER_JENNY_3                     385
#define TRAINER_HEIDI                       386
#define TRAINER_BECKY                       387
#define TRAINER_CAROL                       388
#define TRAINER_NANCY                       389
#define TRAINER_MARTHA                      390
#define TRAINER_DIANA_1                     391
#define TRAINER_CEDRIC                      392
#define TRAINER_IRENE                       393
#define TRAINER_DIANA_2                     394
#define TRAINER_DIANA_3                     395
#define TRAINER_AMY_AND_LIV_1               396
#define TRAINER_GINA_AND_MIA                397
#define TRAINER_MIU_AND_YUKI                398
#define TRAINER_AMY_AND_LIV_2               399
#define TRAINER_AMY_AND_LIV_3               400
#define TRAINER_HUEY                        401
#define TRAINER_EDMOND                      402
#define TRAINER_ERNEST_1                    403
#define TRAINER_DWAYNE                      404
#define TRAINER_PHILLIP                     405
#define TRAINER_LEONARD                     406
#define TRAINER_DUNCAN                      407
#define TRAINER_ERNEST_2                    408
#define TRAINER_ERNEST_3                    409
#define TRAINER_ELI                         410
#define TRAINER_ANNIKA                      411
#define TRAINER_JAZMYN                      412
#define TRAINER_JONAS                       413
#define TRAINER_KAYLEY                      414
#define TRAINER_AURON                       415
#define TRAINER_KELVIN                      416
#define TRAINER_MARLEY                      417
#define TRAINER_REYNA                       418
#define TRAINER_HUDSON                      419
#define TRAINER_CONOR                       420
#define TRAINER_EDWIN_1                     421
#define TRAINER_HECTOR                      422
#define TRAINER_TABITHA_MOSSDEEP            423
#define TRAINER_EDWIN_2                     424
#define TRAINER_EDWIN_3                     425
#define TRAINER_WALLY_VR_1                  426
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    427
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    428
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    429
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   430
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   431
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   432
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   433
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   434
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   435
#define TRAINER_MAY_ROUTE_103_MUDKIP        436
#define TRAINER_MAY_ROUTE_110_MUDKIP        437
#define TRAINER_MAY_ROUTE_119_MUDKIP        438
#define TRAINER_MAY_ROUTE_103_TREECKO       439
#define TRAINER_MAY_ROUTE_110_TREECKO       440
#define TRAINER_MAY_ROUTE_119_TREECKO       441
#define TRAINER_MAY_ROUTE_103_TORCHIC       442
#define TRAINER_MAY_ROUTE_110_TORCHIC       443
#define TRAINER_MAY_ROUTE_119_TORCHIC       444
#define TRAINER_ISAAC_1                     445
#define TRAINER_DAVIS                       446
#define TRAINER_MITCHELL                    447
#define TRAINER_ISAAC_2                     448
#define TRAINER_ISAAC_3                     449
#define TRAINER_LYDIA_1                     450
#define TRAINER_HALLE                       451
#define TRAINER_GARRISON                    452
#define TRAINER_LYDIA_2                     453
#define TRAINER_LYDIA_3                     454
#define TRAINER_JACKSON_1                   455
#define TRAINER_LORENZO                     456
#define TRAINER_SEBASTIAN                   457
#define TRAINER_JACKSON_2                   458
#define TRAINER_JACKSON_3                   459
#define TRAINER_CATHERINE_1                 460
#define TRAINER_JENNA                       461
#define TRAINER_SOPHIA                      462
#define TRAINER_CATHERINE_2                 463
#define TRAINER_CATHERINE_3                 464
#define TRAINER_JULIO                       465
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     466
#define TRAINER_GRUNT_MT_PYRE_4             467
#define TRAINER_GRUNT_JAGGED_PASS           468
#define TRAINER_MARC                        469
#define TRAINER_BRENDEN                     470
#define TRAINER_LILITH                      471
#define TRAINER_CRISTIAN                    472
#define TRAINER_SYLVIA                      473
#define TRAINER_LEONARDO                    474
#define TRAINER_ATHENA                      475
#define TRAINER_HARRISON                    476
#define TRAINER_GRUNT_MT_CHIMNEY_2          477
#define TRAINER_CLARENCE                    478
#define TRAINER_TERRY                       479
#define TRAINER_NATE                        480
#define TRAINER_KATHLEEN                    481
#define TRAINER_CLIFFORD                    482
#define TRAINER_NICHOLAS                    483
#define TRAINER_GRUNT_SPACE_CENTER_3        484
#define TRAINER_GRUNT_SPACE_CENTER_4        485
#define TRAINER_GRUNT_SPACE_CENTER_5        486
#define TRAINER_GRUNT_SPACE_CENTER_6        487
#define TRAINER_GRUNT_SPACE_CENTER_7        488
#define TRAINER_MACEY                       489
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    490
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     491
#define TRAINER_PAXTON                      492
#define TRAINER_ISABELLA                    493
#define TRAINER_GRUNT_WEATHER_INST_5        494
#define TRAINER_TABITHA_MT_CHIMNEY          495
#define TRAINER_JONATHAN                    496
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    497
#define TRAINER_MAY_RUSTBORO_MUDKIP         498
#define TRAINER_MAXIE_MAGMA_HIDEOUT         499
#define TRAINER_MAXIE_MT_CHIMNEY            500
#define TRAINER_TIANA                       501
#define TRAINER_HALEY_1                     502
#define TRAINER_JANICE                      503
#define TRAINER_VIVI                        504
#define TRAINER_HALEY_2                     505
#define TRAINER_HALEY_3                     506
#define TRAINER_SALLY                       507
#define TRAINER_ROBIN                       508
#define TRAINER_ANDREA                      509
#define TRAINER_CRISSY                      510
#define TRAINER_RICK                        511
#define TRAINER_LYLE                        512
#define TRAINER_JOSE                        513
#define TRAINER_DOUG                        514
#define TRAINER_GREG                        515
#define TRAINER_KENT                        516
#define TRAINER_JAMES_1                     517
#define TRAINER_JAMES_2                     518
#define TRAINER_JAMES_3                     519
#define TRAINER_BRICE                       520
#define TRAINER_TRENT_1                     521
#define TRAINER_LENNY                       522
#define TRAINER_LUCAS                       523
#define TRAINER_ALAN                        524
#define TRAINER_CLARK                       525
#define TRAINER_ERIC                        526
#define TRAINER_MIKE                        527
#define TRAINER_TRENT_2                     528
#define TRAINER_TRENT_3                     529
#define TRAINER_DEZ_AND_LUKE                530
#define TRAINER_LEA_AND_JED                 531
#define TRAINER_KIRA_AND_DAN_1              532
#define TRAINER_KIRA_AND_DAN_2              533
#define TRAINER_KIRA_AND_DAN_3              534
#define TRAINER_JOHANNA                     535
#define TRAINER_GERALD                      536
#define TRAINER_VIVIAN                      537
#define TRAINER_DANIELLE                    538
#define TRAINER_HIDEO                       539
#define TRAINER_KEIGO                       540
#define TRAINER_RILEY                       541
#define TRAINER_FLINT                       542
#define TRAINER_ASHLEY                      543
#define TRAINER_WALLY_MAUVILLE              544
#define TRAINER_WALLY_VR_2                  545
#define TRAINER_WALLY_VR_3                  546
#define TRAINER_WALLY_VR_4                  547
#define TRAINER_WALLY_VR_5                  548
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     549
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    550
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    551
#define TRAINER_MAY_LILYCOVE_MUDKIP         552
#define TRAINER_MAY_LILYCOVE_TREECKO        553
#define TRAINER_MAY_LILYCOVE_TORCHIC        554
#define TRAINER_JONAH                       555
#define TRAINER_HENRY                       556
#define TRAINER_ROGER                       557
#define TRAINER_ALEXA                       558
#define TRAINER_RUBEN                       559
#define TRAINER_KOJI_1                      560
#define TRAINER_WAYNE                       561
#define TRAINER_AIDAN                       562
#define TRAINER_REED                        563
#define TRAINER_TISHA                       564
#define TRAINER_TORI_AND_TIA                565
#define TRAINER_KIM_AND_IRIS                566
#define TRAINER_TYRA_AND_IVY                567
#define TRAINER_MEL_AND_PAUL                568
#define TRAINER_JOHN_AND_JAY_1              569
#define TRAINER_JOHN_AND_JAY_2              570
#define TRAINER_JOHN_AND_JAY_3              571
#define TRAINER_RELI_AND_IAN                572
#define TRAINER_LILA_AND_ROY_1              573
#define TRAINER_LILA_AND_ROY_2              574
#define TRAINER_LILA_AND_ROY_3              575
#define TRAINER_LISA_AND_RAY                576
#define TRAINER_CHRIS                       577
#define TRAINER_DAWSON                      578
#define TRAINER_SARAH                       579
#define TRAINER_DARIAN                      580
#define TRAINER_HAILEY                      581
#define TRAINER_CHANDLER                    582
#define TRAINER_KALEB                       583
#define TRAINER_JOSEPH                      584
#define TRAINER_ALYSSA                      585
#define TRAINER_MARCOS                      586
#define TRAINER_RHETT                       587
#define TRAINER_TYRON                       588
#define TRAINER_CELINA                      589
#define TRAINER_BIANCA                      590
#define TRAINER_HAYDEN                      591
#define TRAINER_SOPHIE                      592
#define TRAINER_COBY                        593
#define TRAINER_LAWRENCE                    594
#define TRAINER_WYATT                       595
#define TRAINER_ANGELINA                    596
#define TRAINER_KAI                         597
#define TRAINER_CHARLOTTE                   598
#define TRAINER_DEANDRE                     599
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       600
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       601
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       602
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       603
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       604
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       605
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       606
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       607
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       608
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      609
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      610
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      611
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      612
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      613
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      614
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      615
#define TRAINER_TABITHA_MAGMA_HIDEOUT       616
#define TRAINER_DARCY                       617
#define TRAINER_MAXIE_MOSSDEEP              618
#define TRAINER_PETE                        619
#define TRAINER_ISABELLE                    620
#define TRAINER_ANDRES_1                    621
#define TRAINER_JOSUE                       622
#define TRAINER_CAMRON                      623
#define TRAINER_CORY_1                      624
#define TRAINER_CAROLINA                    625
#define TRAINER_ELIJAH                      626
#define TRAINER_CELIA                       627
#define TRAINER_BRYAN                       628
#define TRAINER_BRANDEN                     629
#define TRAINER_BRYANT                      630
#define TRAINER_SHAYLA                      631
#define TRAINER_KYRA                        632
#define TRAINER_JAIDEN                      633
#define TRAINER_ALIX                        634
#define TRAINER_HELENE                      635
#define TRAINER_MARLENE                     636
#define TRAINER_DEVAN                       637
#define TRAINER_JOHNSON                     638
#define TRAINER_MELINA                      639
#define TRAINER_BRANDI                      640
#define TRAINER_AISHA                       641
#define TRAINER_MAKAYLA                     642
#define TRAINER_FABIAN                      643
#define TRAINER_DAYTON                      644
#define TRAINER_RACHEL                      645
#define TRAINER_LEONEL                      646
#define TRAINER_CALLIE                      647
#define TRAINER_CALE                        648
#define TRAINER_MYLES                       649
#define TRAINER_PAT                         650
#define TRAINER_CRISTIN_1                   651
#define TRAINER_MAY_RUSTBORO_TREECKO        652
#define TRAINER_MAY_RUSTBORO_TORCHIC        653
#define TRAINER_ROXANNE_2                   654
#define TRAINER_ROXANNE_3                   655
#define TRAINER_ROXANNE_4                   656
#define TRAINER_ROXANNE_5                   657
#define TRAINER_BRAWLY_2                    658
#define TRAINER_BRAWLY_3                    659
#define TRAINER_BRAWLY_4                    660
#define TRAINER_BRAWLY_5                    661
#define TRAINER_WATTSON_2                   662
#define TRAINER_WATTSON_3                   663
#define TRAINER_WATTSON_4                   664
#define TRAINER_WATTSON_5                   665
#define TRAINER_FLANNERY_2                  666
#define TRAINER_FLANNERY_3                  667
#define TRAINER_FLANNERY_4                  668
#define TRAINER_FLANNERY_5                  669
#define TRAINER_NORMAN_2                    670
#define TRAINER_NORMAN_3                    671
#define TRAINER_NORMAN_4                    672
#define TRAINER_NORMAN_5                    673
#define TRAINER_WINONA_2                    674
#define TRAINER_WINONA_3                    675
#define TRAINER_WINONA_4                    676
#define TRAINER_WINONA_5                    677
#define TRAINER_TATE_AND_LIZA_2             678
#define TRAINER_TATE_AND_LIZA_3             679
#define TRAINER_TATE_AND_LIZA_4             680
#define TRAINER_TATE_AND_LIZA_5             681
#define TRAINER_JUAN_2                      682
#define TRAINER_JUAN_3                      683
#define TRAINER_JUAN_4                      684
#define TRAINER_JUAN_5                      685
#define TRAINER_ANGELO                      686
#define TRAINER_DARIUS                      687
#define TRAINER_STEVEN                      688
#define TRAINER_ANABEL                      689
#define TRAINER_TUCKER                      690
#define TRAINER_SPENSER                     691
#define TRAINER_GRETA                       692
#define TRAINER_NOLAND                      693
#define TRAINER_LUCY                        694
#define TRAINER_BRANDON                     695
#define TRAINER_ANDRES_2                    696
#define TRAINER_ANDRES_3                    697
#define TRAINER_CORY_2                      698
#define TRAINER_CORY_3                      699
#define TRAINER_PABLO_2                     700
#define TRAINER_PABLO_3                     701
#define TRAINER_KOJI_2                      702
#define TRAINER_KOJI_3                      703
#define TRAINER_CRISTIN_2                   704
#define TRAINER_CRISTIN_3                   705
#define TRAINER_FERNANDO_2                  706
#define TRAINER_FERNANDO_3                  707
#define TRAINER_SAWYER_2                    708
#define TRAINER_SAWYER_3                    709
#define TRAINER_GABRIELLE_2                 710
#define TRAINER_GABRIELLE_3                 711
#define TRAINER_THALIA_2                    712
#define TRAINER_THALIA_3                    713
#define TRAINER_MARIELA                     714
#define TRAINER_ALVARO                      715
#define TRAINER_EVERETT                     716
#define TRAINER_RED                         717
#define TRAINER_LEAF                        718
#define TRAINER_BRENDAN_PLACEHOLDER         719
#define TRAINER_MAY_PLACEHOLDER             720
#define TRAINER_BRENDAN_ROUTE_103_POSTGAME  721
#define TRAINER_MAY_ROUTE_103_POSTGAME      722
#define TRAINER_META_BOY                    723

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      724
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
