.include "data/maps/Route104North/scripts.inc"
.include "data/maps/Route104South/scripts.inc"

.include "data/scripts/pory_scripts/getbadgecount.inc"
.include "data/scripts/pory_scripts/pokemart.inc"

.include "data/scripts/pory_scripts/maps/BattleFrontier_Mart.inc"
.include "data/scripts/pory_scripts/maps/EverGrandeCity_PokemonLeague_1F.inc"
.include "data/scripts/pory_scripts/maps/OldaleTown_Mart.inc"
.include "data/scripts/pory_scripts/maps/TrainerHill_Entrance.inc"
